### ISSUE TITLE
Отображение списка товаров в админке

### ISSUE THREAD

**Issue by nezuma** [nezuma/clicker.rimworlda.ru#9]
В админке у нас такой вот красивый вывод
![image](https://github.com/nezuma/clicker.rimworlda.ru/assets/110791833/38cee043-06ea-4cf0-bde1-15a352f2227c)
Исправить не сложно:
``` css
.output-store {
    flex-wrap: wrap; /* Добавленная строка в style admin.vue */
}
```
Дополнительно добавить надо в product-card-admin.vue 
``` css
.product-card {
    background: #151521;
    width: 200px;
    height: 250px;
    border-radius: 25px;
    margin-bottom: 25px; /* добавленная строка в style product-card-admin.vue */
}
```
Получится это: 
![image](https://github.com/nezuma/clicker.rimworlda.ru/assets/110791833/33a8d099-748b-4cae-8ae7-01563a5a4fdb)
